export const capabilityCategories = [
  { id:"operations", label:"Center Control & Operations", outcome:"Move each visit through the normal estimate-first path while preserving customer and vehicle context.", features:[
    ["LayoutDashboard","Center Control dashboard","Owners see appointments, estimates, approvals, active Repair Orders, financial signals, and workflow handoffs in one operating view."],
    ["CalendarDays","Appointments and intake","Online, phone, walk-in, and scheduled visits capture the concern and lead into customer, vehicle, and estimate preparation."],
    ["Globe2","Branded booking entry","Customers can start from the shop’s branded website and booking experience before staff continue intake."],
    ["Users","Customer profiles and contact records","Staff maintain contact context and controlled data-quality support without exposing internal maintenance tools."],
    ["CarFront","Multi-vehicle profiles and timelines","Mileage, photos, recommendations, and service history follow each vehicle into the next estimate."],
    ["FileUp","Controlled customer import","Owners can bring customer records into the shop workspace and review data quality before daily use."],
    ["FileCheck2","Estimate-first intake","The normal path prepares and sends an estimate before approved work becomes a Repair Order."],
    ["ClipboardList","Repair Orders and job status","Approved estimates convert to trackable work; authorized shops can also create an RO directly when appropriate."],
    ["ArrowRightLeft","Connected document handoffs","Customer, vehicle, estimate, RO, invoice, payment record, and history retain their source relationships."]], demo:[["Today","12 visits"],["Estimates","6"],["Active ROs","8"]] },
  { id:"team", label:"Team & Technicians", outcome:"Keep mechanics and office staff assigned, timed, status-aware, and consistently documented.", features:[
    ["UsersRound","Mechanics and office staff","Owners maintain the people records needed for assignments and shop operations."],
    ["KeyRound","Shop-scoped PIN access","Technicians enter their shop-specific portal without gaining owner-level workspace access."],
    ["Wrench","Technician Portal and assigned jobs","Technicians see the Repair Orders assigned to them and continue the approved work."],
    ["Clock3","Clock in/out and time tracking","Recorded work time supports job visibility, productivity context, and payroll summaries."],
    ["ChartNoAxesCombined","Productivity context","Owners can compare technician activity and shop performance without promising payroll automation."],
    ["WalletCards","Payroll summaries and management","The shop can review recorded time and payroll context; no remittance or direct deposit is claimed."],
    ["Camera","Required five-photo record","Technicians document four exterior angles plus the dashboard condition before completing the job."]], demo:[["Assigned","3 jobs"],["Clocked","6h 24m"],["Photos","5 / 5"]] },
  { id:"parts", label:"Parts & Inventory", outcome:"Find, count, import, and connect parts to estimates, Repair Orders, and invoices.", features:[
    ["PackageSearch","Parts inventory","Staff track available parts and use them in customer work."],
    ["TriangleAlert","Low-stock visibility","Owners can spot items that need attention before they delay a Repair Order."],
    ["PackagePlus","Quick stock updates","Staff adjust quantities quickly as parts are received or used."],
    ["ScanBarcode","Barcode and QR scanning","Technicians or parts staff can identify inventory items with supported device scanning."],
    ["FileUp","CSV import","Shops can bring structured parts lists into inventory with a controlled import flow."],
    ["Download","RockAuto import","Supported RockAuto data can be imported into the parts workflow for shop use."],
    ["Search","Vehicle and VIN parts lookup","Staff search catalog context for the correct vehicle before adding guidance or items."],
    ["Link2","Parts in the document workflow","Selected parts move through Estimate → Repair Order → Invoice context with the job."]], demo:[["In stock","428"],["Low stock","7"],["Linked","14 jobs"]] },
  { id:"financials", label:"Documents, Financials & Reports", outcome:"Keep approved scope, completed work, invoice records, recorded payments, and reporting context connected.", features:[
    ["FileCheck2","Estimate lifecycle","Draft labor, parts, taxes, and totals; send for approval or decline; track expiry and conversion."],
    ["ClipboardList","Approved Estimate to Repair Order","Approved scope becomes assigned work with Waiting, In Progress, Waiting for Parts, Completed, and Delivered states."],
    ["Files","Unified invoice workflow","Completed work moves through Work & Line Items → Taxes & Totals → Review & Delivery without leaving the source context."],
    ["Signature","Approval and invoice signing","Supported customer decisions and signatures remain connected to the appropriate document."],
    ["History","Payment history and receipts","The shop records payment methods and receipt history; this does not claim payment processing or bank settlement."],
    ["Calculator","Amount paid and balance","Owners track invoice totals, recorded payments, and the remaining balance."],
    ["Printer","Print, PDF, and email delivery","Customer-ready documents and reports can be printed, downloaded, or delivered through supported email flows."],
    ["ChartSpline","Insights, Overview, and Profit & Loss","Owners review financial overview, average-job context, revenue, and shop performance."],
    ["CircleDollarSign","Daily and productivity reports","Cash, card, and e-transfer records support end-of-day, printable/PDF, and technician productivity summaries—not tax filing or accounting certification."]], demo:[["Revenue • Demo","$18.4k"],["Average job","$612"],["Reports","Ready"]] },
  { id:"customer", label:"Customer Experience", outcome:"Give customers a branded, private path from booking through decisions, documents, and service history.", features:[
    ["Globe2","Branded booking entry","Customers can request a visit through the shop’s branded booking experience."],
    ["ShieldCheck","Secure activation and passcode","The customer activates access and creates a private passcode for their portal."],
    ["FolderOpen","Four-widget customer dashboard","Repair Orders, Estimates, Invoices, and Appointments appear in that order with customer-safe status and history."],
    ["BadgeCheck","Estimate approval or decline","Where securely supported, the customer records a decision that can unlock the Repair Order transition."],
    ["ReceiptText","Invoice and receipt access","Customers can review customer-safe invoice, amount-paid, balance, and receipt records."],
    ["MessagesSquare","Messaging and Chat Inbox","Customers and the shop keep service communication connected to the relationship."],
    ["KeyRound","Profile and security controls","Customer-facing controls protect access while internal notes, costs, discount math, and other shop data remain hidden."]], demo:[["Portal","Private"],["Messages","3 new"],["History","11 visits"]] },
  { id:"diagnostics", label:"LBC AI & Office Assistance", outcome:"Bring vehicle-aware scan evidence and operational assistance into decisions that people review.", features:[
    ["Cable","LBC AI Scanner connection","Technicians connect compatible OBD2 hardware, currently targeting Vgate iCar Pro 2S BLE where applicable."],
    ["ScanLine","VIN, mileage, and vehicle identity","The scanner decodes VIN through the vehicle-data flow, supports manual entry, and keeps Vehicle Identified context visible."],
    ["Activity","Scan, Live Data, and Tech Mode","Use guided health scanning, supported sensor streaming, or advanced professional controls only where vehicle and hardware support them."],
    ["Binary","DTC guidance","Each code can include likely causes, verification steps, labor range, parts guidance, and customer- and mechanic-level explanations."],
    ["FileChartColumn","Health workflow and report","Background polling supports an approximately two-minute workflow with readiness, DTC severity, snapshot, summary, findings, and next steps."],
    ["Link2","Scanner actions","Supported results can be saved to a Repair Order, used to create an Estimate, or printed for review."],
    ["Bot","Contextual LBC Auto AI chat","Technicians can ask follow-up questions with scan, vehicle, document, labor, and parts context attached."],
    ["Headset","Office Assistant","Operational assistance helps staff work through shop tasks while people remain responsible for decisions."]], demo:[["Vehicle","Identified"],["DTCs • Demo","2"],["Report","Ready"]], scanner:true }
];