import React, { useRef, useState } from "react";
import { Activity, ArrowRightLeft, BadgeCheck, Binary, BookOpenCheck, Bot, Cable, Calculator, CalendarDays, Camera, CarFront, ChartNoAxesCombined, ChartSpline, CircleDollarSign, ClipboardList, Clock3, Download, FileChartColumn, FileCheck2, FileUp, Files, FolderOpen, Globe2, Headset, History, KeyRound, Landmark, LayoutDashboard, Link2, MessagesSquare, PackagePlus, PackageSearch, Printer, ReceiptText, ScanBarcode, ScanLine, Search, ShieldCheck, Signature, TriangleAlert, Users, UsersRound, WalletCards, Wrench } from "lucide-react";
import { capabilityCategories } from "./capabilityData";
import CapabilityDemo from "./CapabilityDemo";
import ScannerDetails from "./ScannerDetails";
import "./CapabilityMap.css";

const iconMap={Activity,ArrowRightLeft,BadgeCheck,Binary,BookOpenCheck,Bot,Cable,Calculator,CalendarDays,Camera,CarFront,ChartNoAxesCombined,ChartSpline,CircleDollarSign,ClipboardList,Clock3,Download,FileChartColumn,FileCheck2,FileUp,Files,FolderOpen,Globe2,Headset,History,KeyRound,Landmark,LayoutDashboard,Link2,MessagesSquare,PackagePlus,PackageSearch,Printer,ReceiptText,ScanBarcode,ScanLine,Search,ShieldCheck,Signature,TriangleAlert,Users,UsersRound,WalletCards,Wrench};
export default function CapabilityMap(){
  const [active,setActive]=useState(0), refs=useRef([]), category=capabilityCategories[active];
  const move=next=>{const value=(next+capabilityCategories.length)%capabilityCategories.length;setActive(value);requestAnimationFrame(()=>refs.current[value]?.focus());};
  const keys=e=>{if(e.key==="ArrowRight")move(active+1);if(e.key==="ArrowLeft")move(active-1);if(e.key==="Home")move(0);if(e.key==="End")move(capabilityCategories.length-1);};
  return <section id="capabilities" className="lp-section lp-capabilities" aria-labelledby="capabilities-title"><div className="lp-container"><div className="lp-section-head"><span className="lp-eyebrow">EVERYTHING LBC AUTO INCLUDES</span><h2 id="capabilities-title">Complete capability, organized around outcomes.</h2><p>Explore how operations, people, inventory, financial records, customer experience, and repair context stay connected.</p></div><div className="lp-cap-tabs" role="tablist" aria-label="Capability categories" onKeyDown={keys}>{capabilityCategories.map((item,i)=><button ref={el=>refs.current[i]=el} key={item.id} role="tab" aria-selected={active===i} aria-controls="capability-panel" tabIndex={active===i?0:-1} onClick={()=>setActive(i)}>{item.label}</button>)}</div><div id="capability-panel" className="lp-cap-panel" role="tabpanel"><div><span className="lp-cap-count">{String(active+1).padStart(2,"0")} / 06</span><h3>{category.label}</h3><p>{category.outcome}</p><div className="lp-cap-list">{category.features.map(([icon,label,copy])=>{const Icon=iconMap[icon];return <div key={label}><Icon aria-hidden="true"/><span><strong>{label}</strong><p>{copy}</p></span></div>})}</div>{category.scanner&&<ScannerDetails/>}</div><CapabilityDemo category={category}/></div></div></section>;
}