export const tourSteps = [
  { title: "Center Control Dashboard", eyebrow: "Owner command center", description: "See today’s workload, shop performance, and every handoff from one connected view. Each shop sees only its own workspace data.", bullets: ["Live operational overview", "Connected daily workflow", "Shop-isolated records"], metrics: [["Appointments", "12"], ["Open orders", "8"], ["Ready today", "4"]], flow: ["Booked", "In service", "Ready"], records: ["8:30 • Vehicle intake", "10:00 • Estimate review", "2:30 • Delivery"] },
  { title: "Customers & Vehicles", eyebrow: "A complete service story", description: "Customer profiles connect every vehicle’s mileage, photos, recommendations, and service history to the work that follows.", bullets: ["Vehicle history by customer", "Mileage and service records", "Photos and recommendations"], metrics: [["Vehicles", "2"], ["Visits", "11"], ["Open items", "3"]], flow: ["Profile", "Vehicle", "History"], records: ["2019 Sample Sedan • 84,210 km", "Brake service • Completed", "Tire rotation • Recommended"] },
  { title: "Appointments & Intake", eyebrow: "From booking to the bay", description: "Bring online, phone, walk-in, and scheduled arrivals into a consistent intake process, then turn the visit into active work.", bullets: ["Flexible booking sources", "Arrival and vehicle intake", "Clear job assignment"], metrics: [["Arriving", "6"], ["Checked in", "3"], ["Assigned", "2"]], flow: ["Appointment", "Intake", "Repair Order"], records: ["9:00 • Sample Customer", "Concern: steering vibration", "Assigned bay • Demo"] },
  { title: "Repair Orders & Estimates", eyebrow: "Clear scope and approval", description: "Organize requested work, labor and parts, technician assignment, approvals, and status without losing the original customer concern.", bullets: ["Repair order status tracking", "Customer-ready estimates", "Approval connected to work"], metrics: [["Labor", "$420"], ["Parts", "$285"], ["Estimate", "$761"]], flow: ["Repair Order", "Estimate", "Approval"], records: ["Front brake service", "Pads and rotors • Sample", "Customer approval • Pending"] },
  { title: "Technician Workflow", eyebrow: "Focused work, documented well", description: "Technicians use shop-specific PIN access to see assigned jobs, track time, and complete a consistent photo record for each vehicle.", bullets: ["Scoped shop PIN access", "Assigned jobs and time tracking", "Required professional documentation"], metrics: [["Assigned", "3"], ["Clocked", "1h 42m"], ["Photos", "5 / 5"]], flow: ["Assigned", "In progress", "Documented"], records: ["Front left exterior", "Front right exterior", "Rear left exterior", "Rear right exterior", "Dashboard condition"] },
  { title: "Invoices & Customer Portal", eyebrow: "Review and delivery in context", description: "Move from completed work to a reviewed invoice, then give customers a secure place to follow records and communication.", bullets: ["Work & Line Items → Taxes & Totals → Review & Delivery", "Demo paid and balance states", "Private repair records and messages"], metrics: [["Invoice • Demo", "$761"], ["Amount paid • Demo", "$300"], ["Balance • Demo", "$461"]], flow: ["Line Items", "Totals", "Delivery"], records: ["Repair orders and estimates", "Invoices and appointments", "Secure shop messages"] },
  { title: "Diagnostics & LBC Auto AI", eyebrow: "Repair context, connected", description: "Combine OBD2 diagnostics, VIN and vehicle context, DTC analysis, labor and parts guidance, and report generation in the workflow.", bullets: ["Vehicle-aware diagnostic context", "DTC and repair guidance", "Reports for clearer decisions"], metrics: [["VIN context", "Ready"], ["DTCs • Demo", "2"], ["Report", "Draft"]], flow: ["Scan", "Analyze", "Report"], records: ["P0301 • Sample code", "Check ignition and fuel context", "AI assists; technician verifies"] }
];

export const flowStages = [
  ["Appointment", "Capture the visit, concern, date, and arrival plan."], ["Customer & Vehicle", "Connect the person, vehicle, mileage, and history."], ["Repair Order", "Turn intake into assigned, trackable shop work."], ["Estimate", "Present clear labor, parts, and proposed work."], ["Approval", "Keep the customer decision tied to the estimate."], ["Technician Work", "Track assigned work, time, status, and photos."], ["Invoice", "Review line items, totals, delivery, and balance."], ["Customer History", "Preserve the completed service story for next time."]
];

export const proofItems = [
  ["Center Control", "Run the day without chasing disconnected screens.", "Appointments, active work, financial signals, and customer communication stay visible in one operating view."],
  ["Customer & Vehicle History", "Start every visit with better context.", "Mileage, photos, recommendations, and prior service follow the vehicle across the workflow."],
  ["Repair Orders, Estimates & Invoices", "Keep scope, approval, work, and billing connected.", "Move through the financial workflow in context while preserving the original job story."],
  ["Technician Portal", "Give technicians a focused view of assigned work.", "Shop-specific PIN access, time tracking, job status, and required photo documentation support a consistent process."],
  ["Secure Customer Portal", "Keep customers informed without exposing shop operations.", "Verified activation and a customer-created passcode provide private access to approvals, status, records, and messages."],
  ["Diagnostics & LBC Auto AI", "Bring scan context into practical shop decisions.", "Use vehicle context, DTC analysis, guidance, and reports as technician-reviewed assistance—not an infallible diagnosis."]
];