export const tourSteps = [
  { title: "Center Control Dashboard", eyebrow: "Owner command center", description: "See today’s workload, financial performance, technician productivity, and every handoff from one connected view. Insights, Overview, Profit & Loss, payment-method and end-of-day reporting support printable and PDF-ready shop reviews.", bullets: ["Operational and financial overview", "Performance, productivity, and reporting context", "Office Assistant support with shop-isolated records"], metrics: [["Appointments", "12"], ["Open orders", "8"], ["Day total • Demo", "$4.8k"]], flow: ["Overview", "Insights", "Reports"], records: ["8:30 • Vehicle intake", "10:00 • Profit & Loss review", "2:30 • End-of-day report"] },
  { title: "Customers & Vehicles", eyebrow: "A complete service story", description: "Complete customer profiles connect multiple vehicles, mileage, photos, recommendations, and service timelines to every future visit, with controlled import and contact-data quality support.", bullets: ["Multi-vehicle customer history", "Mileage, photos, recommendations, and service timelines", "Controlled customer import and data cleanup"], metrics: [["Vehicles", "2"], ["Visits", "11"], ["Open items", "3"]], flow: ["Profile", "Vehicles", "Timeline"], records: ["2019 Sample Sedan • 84,210 km", "Brake service • Completed", "Tire rotation • Recommended"] },
  { title: "Appointments & Intake", eyebrow: "From booking to the bay", description: "Bring branded online booking, phone, walk-in, and scheduled arrivals into a consistent intake process, then turn the visit into active work.", bullets: ["Branded shop website and booking entry", "Arrival and vehicle intake", "Appointment → Intake → Repair Order continuity"], metrics: [["Arriving", "6"], ["Checked in", "3"], ["Assigned", "2"]], flow: ["Appointment", "Intake", "Repair Order"], records: ["9:00 • Sample Customer", "Concern: steering vibration", "Assigned bay • Demo"] },
  { title: "Repair Orders & Estimates", eyebrow: "Clear scope through delivery", description: "Keep requested work, labor, parts, approvals, signatures, technician assignment, invoice delivery, recorded payments, receipts, and balances connected from intake through completion.", bullets: ["RO → Estimate → Approval → Technician Work → Invoice", "Customer approval and invoice signing", "Tax and totals, balance history, print, PDF, and email delivery"], metrics: [["Labor • Demo", "$420"], ["Parts • Demo", "$285"], ["Balance • Demo", "$461"]], flow: ["Repair Order", "Approval", "Invoice"], records: ["Front brake service", "Customer approval • Pending", "Receipt history • Sample record"] },
  { title: "Technician & Team Workflow", eyebrow: "Focused work, documented well", description: "Manage mechanics and office staff while technicians use shop-specific PIN access for assigned jobs, clock in/out, time tracking, productivity context, payroll summaries, and required documentation.", bullets: ["Team management and scoped shop PIN access", "Assignments, time tracking, and payroll summaries", "Four exterior angles plus dashboard-condition photo"], metrics: [["Assigned", "3"], ["Clocked", "1h 42m"], ["Photos", "5 / 5"]], flow: ["Assigned", "Clocked in", "Documented"], records: ["Front left exterior", "Front right exterior", "Rear left exterior", "Rear right exterior", "Dashboard condition"] },
  { title: "Invoices, Communication & Portal", eyebrow: "Review, delivery, and customer clarity", description: "Review and deliver invoices in context, manage signing and payment records, and give customers a secure place for customer-safe service history and communication.", bullets: ["Work & Line Items → Taxes & Totals → Review & Delivery", "Invoice signing, payment history, receipts, print, and email", "Private portal records, appointments, Chat Inbox, and messaging"], metrics: [["Invoice • Demo", "$761"], ["Amount paid • Demo", "$300"], ["Balance • Demo", "$461"]], flow: ["Review", "Delivery", "Portal"], records: ["RO, estimate, invoice, and appointment history", "Customer-safe receipt access", "Secure shop messages • Internal data hidden"] },
  { title: "Parts, Diagnostics & LBC Auto AI", eyebrow: "Inventory and repair context, connected", description: "Connect parts inventory and vehicle/VIN lookup with OBD2 diagnostics, DTCs, supported live data, technician-reviewed guidance, and report generation.", bullets: ["Low-stock visibility, quick updates, barcode and QR scanning", "CSV and RockAuto import plus vehicle/VIN parts lookup", "LBC Auto AI and Office Assistant provide guidance—not guaranteed outcomes"], metrics: [["Low stock • Demo", "7"], ["DTCs • Demo", "2"], ["Report", "Draft"]], flow: ["Find parts", "Diagnose", "Report"], records: ["Inventory item • Sample", "P0301 • Sample code", "AI assists; technician verifies"] }
];

export const flowStages = [
  ["Appointment", "Capture the visit, concern, date, and arrival plan."], ["Customer & Vehicle", "Connect the person, vehicle, mileage, and history."], ["Repair Order", "Turn intake into assigned, trackable shop work."], ["Estimate", "Present clear labor, parts, and proposed work."], ["Approval", "Keep the customer decision tied to the estimate."], ["Technician Work", "Track assigned work, time, status, and photos."], ["Invoice", "Review line items, totals, delivery, and balance."], ["Customer History", "Preserve the completed service story for next time."]
];

export const proofItems = [
  ["Center Control", "Run the day without chasing disconnected screens.", "Appointments, active work, financial signals, and customer communication stay visible in one operating view."],
  ["Customer & Vehicle History", "Start every visit with better context.", "Mileage, photos, recommendations, and prior service follow the vehicle across the workflow."],
  ["Repair Orders, Estimates & Invoices", "Keep scope, approval, work, and billing connected.", "Move through the financial workflow in context while preserving the original job story."],
  ["Technician Portal", "Give technicians a focused view of assigned work.", "Shop-specific PIN access, time tracking, job status, and required photo documentation support a consistent process."],
  ["Secure Customer Portal", "Keep customers informed without exposing shop operations.", "Verified activation and a customer-created passcode provide private access to approvals, status, records, and messages."],
  ["Diagnostics & LBC Auto AI", "Bring scan context into practical shop decisions.", "Use vehicle context, DTC analysis, guidance, and reports as technician-reviewed assistance—not an infallible diagnosis."]
];