import React, { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { CalendarCheck, Trash2 } from "lucide-react";

export default function CalibrationPanel({ machines, calibrations, onCreate, onUpdate, onDelete }) {
  const [form,setForm]=useState({machine_id:"",calibration_type:"",calibrated_by:"",calibration_date:"",next_due_date:"",status:"unknown"});
  const save=async()=>{await onCreate(form);setForm({...form,calibration_type:"",calibrated_by:""});};
  return <div className="grid xl:grid-cols-[360px_1fr] gap-4"><section className="rounded-xl border border-slate-800 bg-slate-900 p-5 space-y-3"><h2 className="font-bold text-white">Add Calibration Record</h2><p className="text-xs text-slate-400">Basic tracking only. LBC does not perform or verify machine calibration.</p><select value={form.machine_id} onChange={e=>setForm({...form,machine_id:e.target.value})} className="h-9 w-full rounded border border-slate-700 bg-slate-950 px-3 text-white"><option value="">Select machine</option>{machines.map(m=><option key={m.id} value={m.id}>{m.make} {m.model}</option>)}</select><Input value={form.calibration_type} onChange={e=>setForm({...form,calibration_type:e.target.value})} placeholder="Calibration type" className="bg-slate-950 border-slate-700 text-white"/><Input value={form.calibrated_by} onChange={e=>setForm({...form,calibrated_by:e.target.value})} placeholder="Performed by" className="bg-slate-950 border-slate-700 text-white"/><div className="grid grid-cols-2 gap-2"><Input type="date" value={form.calibration_date} onChange={e=>setForm({...form,calibration_date:e.target.value})} className="bg-slate-950 border-slate-700 text-white"/><Input type="date" value={form.next_due_date} onChange={e=>setForm({...form,next_due_date:e.target.value})} className="bg-slate-950 border-slate-700 text-white"/></div><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="h-9 w-full rounded border border-slate-700 bg-slate-950 px-3 text-white">{["current","due_soon","expired","unknown"].map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select><Button onClick={save} disabled={!form.machine_id||!form.calibration_type}><CalendarCheck/>Save Record</Button></section><section className="space-y-3"><h2 className="font-bold text-white">Calibration History</h2>{calibrations.length===0?<div className="rounded-xl border border-dashed border-slate-700 p-8 text-center text-slate-500">No calibration records yet.</div>:calibrations.map(record=><div key={record.id} className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 rounded-xl border border-slate-800 bg-slate-900 p-4"><div><p className="font-semibold text-white">{machines.find(m=>m.id===record.machine_id)?.model||"Machine"} · {record.calibration_type}</p><p className="text-xs text-slate-400">{record.calibration_date||"Date unknown"} · Next due {record.next_due_date||"not set"} · {record.calibrated_by||"Technician not recorded"}</p></div><div className="flex items-center gap-2"><select value={record.status} onChange={e=>onUpdate(record.id,{status:e.target.value})} className="h-8 rounded border border-slate-700 bg-slate-950 px-2 text-xs text-cyan-300">{["current","due_soon","expired","unknown"].map(x=><option key={x} value={x}>{x}</option>)}</select><Button size="icon" variant="ghost" className="text-rose-400" onClick={()=>onDelete(record.id)}><Trash2/></Button></div></div>)}</section></div>;
}