import React, { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { ALIGNMENT_ROWS } from "@/lib/alignment/constants";
import { Save } from "lucide-react";

const fields = ["before_value","after_value","spec_min","spec_max"];
const num = value => value === "" || value == null ? undefined : Number(value);
function result(row) { const after=num(row.after_value), min=num(row.spec_min), max=num(row.spec_max), confidence=num(row.confidence); if (row.source !== "manual" && (confidence == null || confidence < .8)) return ["unverified",true]; if (min==null || max==null) return ["no_spec",false]; if (after==null) return ["adjust",false]; return after>=min&&after<=max?["pass",false]:["out_of_range",false]; }
export default function MeasurementGrid({ session, measurements, onSave }) {
  const [rows,setRows]=useState([]),[saving,setSaving]=useState(false);
  useEffect(()=>setRows(ALIGNMENT_ROWS.map(def=>{const old=measurements.find(m=>m.axle===def.axle&&m.parameter===def.parameter&&m.side===def.side);return {...def,before_value:"",after_value:"",spec_min:"",spec_max:"",unit:"degrees",source:session?.created_from==="manual"?"manual":"unknown",confidence:session?.created_from==="manual"?1:"",...old};})),[session,measurements]);
  const change=(index,key,value)=>setRows(current=>current.map((r,i)=>i===index?{...r,[key]:value}:r));
  const save=async()=>{setSaving(true);await onSave(rows.map(({key,label,id,...row})=>{const [status,requires_verification]=result(row);return {...row,...Object.fromEntries(fields.map(f=>[f,num(row[f])])),confidence:num(row.confidence),status,requires_verification};}));setSaving(false);};
  return <div className="space-y-3"><div><h2 className="text-lg font-bold text-white">Before / After Measurements</h2><p className="text-sm text-gray-400">Enter measured values and source specs. Blank specs remain clearly marked as unavailable.</p></div><div className="overflow-x-auto rounded-xl border border-gray-800"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-gray-900 text-gray-400"><tr><th className="p-3 text-left">Position</th>{["Before","After","Spec min","Spec max","Source","Confidence","Result"].map(x=><th key={x} className="p-3 text-left">{x}</th>)}</tr></thead><tbody>{rows.map((row,index)=>{const [status,verify]=result(row);return <tr key={row.key} className="border-t border-gray-800 bg-gray-950/50"><td className="p-3 text-white font-medium">{row.label}</td>{fields.map(field=><td key={field} className="p-2"><input type="number" step="0.01" value={row[field]??""} onChange={e=>change(index,field,e.target.value)} className="w-24 rounded border border-gray-700 bg-gray-800 px-2 py-1.5 text-white" /></td>)}<td className="p-2"><select value={row.source} onChange={e=>change(index,"source",e.target.value)} className="rounded border border-gray-700 bg-gray-800 px-2 py-1.5 text-white"><option value="manual">Manual</option><option value="pdf_extract">PDF</option><option value="ocr">OCR</option><option value="csv_import">CSV</option><option value="screenshot">Screenshot</option><option value="unknown">Unknown</option></select></td><td className="p-2"><input type="number" min="0" max="1" step="0.01" value={row.confidence??""} onChange={e=>change(index,"confidence",e.target.value)} className="w-20 rounded border border-gray-700 bg-gray-800 px-2 py-1.5 text-white" /></td><td className="p-2"><Status value={status} verify={verify} /></td></tr>})}</tbody></table></div><Button onClick={save} disabled={saving} className="bg-sky-600 hover:bg-sky-700"><Save />{saving?"Saving…":"Save Measurements"}</Button></div>;
}
function Status({value,verify}){const cls={pass:"bg-emerald-500/15 text-emerald-400",out_of_range:"bg-rose-500/15 text-rose-400",adjust:"bg-amber-500/15 text-amber-400",no_spec:"bg-gray-700 text-gray-300",unverified:"bg-amber-500/15 text-amber-300"}[value];const label={pass:"Pass",out_of_range:"Out of range",adjust:"Adjustment pending",no_spec:"No spec available",unverified:"Requires verification"}[value];return <span className={`inline-flex rounded-full px-2 py-1 text-xs font-bold ${cls}`}>{verify?"Requires verification":label}</span>}