import React, { useEffect, useState } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { FileText, Link2, Printer, Receipt, Save, Upload } from "lucide-react";

const safe=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
export default function ReportBuilder({ session, customer, vehicle, machine, order, measurements, shop, report, onSave, navigate }) {
  const [notes,setNotes]=useState(report?.technician_notes||""),[visible,setVisible]=useState(report?.customer_visible||false),[ack,setAck]=useState(report?.disclaimer_acknowledged||false),[photos,setPhotos]=useState(report?.photo_urls||[]),[saving,setSaving]=useState(false);
  useEffect(()=>{setNotes(report?.technician_notes||"");setVisible(report?.customer_visible||false);setAck(report?.disclaimer_acknowledged||false);setPhotos(report?.photo_urls||[]);},[report,session?.id]);
  if(!session)return <Empty />;
  const rows=measurements.map(m=>`<tr><td>${safe(`${m.axle} ${m.side} ${m.parameter}`)}</td><td>${safe(m.before_value??"—")}</td><td>${safe(m.after_value??"—")}</td><td>${m.spec_min==null||m.spec_max==null?"No spec available":safe(`${m.spec_min} to ${m.spec_max}`)}</td><td>${safe(m.requires_verification?"Requires verification":m.status)}</td></tr>`).join("");
  const print=()=>{const w=window.open("","_blank");if(!w)return;w.document.write(`<html><head><title>Alignment Report</title><style>body{font-family:Arial;padding:30px;color:#111}h1{color:#0284c7}table{width:100%;border-collapse:collapse}th,td{padding:8px;border:1px solid #ddd;text-align:left}.note{margin-top:20px}.warn{margin-top:25px;padding:12px;border:1px solid #d97706;background:#fffbeb;font-size:12px}</style></head><body><h1>${safe(shop?.business_name||"LBC Auto")}</h1><h2>Before / After Alignment Report</h2><p>${safe(customer?.full_name)} · ${safe(`${vehicle?.year||""} ${vehicle?.make||""} ${vehicle?.model||""}`)} · VIN ${safe(vehicle?.vin||"Not recorded")} · Mileage ${safe(vehicle?.mileage??"Not recorded")}</p><p>Machine: ${safe(machine?`${machine.make} ${machine.model}`:"Not recorded")} · Technician: ${safe(session.technician_name||"Not recorded")} · ${new Date().toLocaleDateString()}</p><table><thead><tr><th>Measurement</th><th>Before</th><th>After</th><th>Specification</th><th>Result</th></tr></thead><tbody>${rows}</tbody></table><p class="note"><b>Technician notes:</b> ${safe(notes||"None")}</p><p>Source: ${safe(session.created_from)} · Confidence: ${safe(session.source_confidence??"Not supplied")}</p><div class="warn">Source measurements are not verified by LBC Auto. Final alignment accuracy, calibration, and vehicle release are the responsibility of the performing technician and shop. Phase 1 does not control alignment hardware.</div></body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),250);};
  const upload=async e=>{const files=[...(e.target.files||[])];const urls=[];for(const file of files){const {file_url}=await base44.integrations.Core.UploadFile({file});urls.push(file_url);}setPhotos(p=>[...p,...urls]);};
  const save=async()=>{setSaving(true);await onSave({report_title:"Before / After Alignment Report",technician_notes:notes,photo_urls:photos,customer_visible:visible,disclaimer_acknowledged:ack});setSaving(false);};
  const query=new URLSearchParams({customerId:session.customer_id,customerName:customer?.full_name||"",vehicleId:session.vehicle_id,vehicleInfo:`${vehicle?.year||""} ${vehicle?.make||""} ${vehicle?.model||""}`.trim(),serviceReason:"Wheel Alignment",notes:`Alignment session ${session.id}`}).toString();
  return <div className="space-y-4 pb-24"><div className="rounded-xl border border-sky-500/30 bg-gray-900 p-5"><h2 className="text-xl font-bold text-white">{shop?.business_name||"LBC Auto"}</h2><p className="text-sky-400 font-semibold">Before / After Alignment Report</p><p className="text-sm text-gray-400 mt-2">{customer?.full_name} · {vehicle?.year} {vehicle?.make} {vehicle?.model} · VIN {vehicle?.vin||"Not recorded"} · Mileage {vehicle?.mileage??"Not recorded"}</p><p className="text-xs text-gray-500 mt-1">Machine: {machine?`${machine.make} ${machine.model}`:"Not recorded"} · Technician: {session.technician_name||"Not recorded"}</p></div><div className="overflow-x-auto rounded-xl border border-gray-800"><table className="w-full min-w-[750px] text-sm"><thead className="bg-gray-900 text-gray-400"><tr><th className="p-3 text-left">Measurement</th><th>Before</th><th>After</th><th>Specification</th><th>Result</th></tr></thead><tbody>{measurements.map(m=><tr key={m.id} className="border-t border-gray-800"><td className="p-3 capitalize text-white">{m.axle} {m.side} {m.parameter.replace("_"," ")}</td><td>{m.before_value??"—"}</td><td>{m.after_value??"—"}</td><td>{m.spec_min==null||m.spec_max==null?"No spec available":`${m.spec_min} to ${m.spec_max}`}</td><td className="capitalize">{m.requires_verification?"Requires verification":m.status.replaceAll("_"," ")}</td></tr>)}</tbody></table></div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Technician notes" className="w-full min-h-24 rounded-lg border border-gray-700 bg-gray-900 p-3 text-white" /><label className="flex items-center gap-2 text-sm text-gray-300"><input type="file" multiple accept="image/*" onChange={upload} className="hidden" id="alignment-photos" /><Button asChild variant="outline"><span><Upload /> Attach Photos</span></Button>{photos.length} attached</label>{photos.length>0&&<div className="flex gap-2 overflow-x-auto">{photos.map(url=><img key={url} src={url} alt="Alignment attachment" className="h-20 w-28 rounded-lg border border-gray-700 object-cover" />)}</div>}<label className="flex gap-2 text-sm text-gray-300"><input type="checkbox" checked={visible} onChange={e=>setVisible(e.target.checked)} /> Customer Visible</label><label className="flex gap-2 text-sm text-amber-200"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)} /> I acknowledge the source measurement and calibration disclaimer.</label>
    <div className="sticky bottom-0 z-20 grid sm:grid-cols-3 lg:grid-cols-6 gap-2 border border-gray-800 bg-gray-950/95 p-3 rounded-xl"><Button onClick={save} disabled={!ack||saving}><Save />Save Report</Button><Button variant="outline" onClick={save} disabled={!order||!ack}><Link2 />Link to Repair Order</Button><Button variant="outline" onClick={()=>navigate(`/Estimates?${query}`)}><FileText />Add to Estimate</Button><Button variant="outline" onClick={()=>navigate(`/Invoices?${query}`)}><Receipt />Add to Invoice</Button><Button variant="outline" onClick={print}><Printer />Print Report</Button><Button variant="outline" onClick={()=>navigate(order?`/RepairOrderDetail/${order.id}`:"/RepairOrders")}>RO Financial Flow</Button></div></div>;
}
function Empty(){return <div className="rounded-xl border border-dashed border-gray-700 p-10 text-center text-gray-400">Create a session and enter measurements before building a report.</div>}