import React, { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import { useToast } from "@/components/ui/use-toast";
import AlignmentWorkspaceNav from "@/components/alignment/AlignmentWorkspaceNav";
import PhaseGateBanner from "@/components/alignment/PhaseGateBanner";
import AlignmentOverview from "@/components/alignment/AlignmentOverview";
import StartSession from "@/components/alignment/StartSession";
import MeasurementGrid from "@/components/alignment/MeasurementGrid";
import ReportBuilder from "@/components/alignment/ReportBuilder";
import MachinesPanel from "@/components/alignment/MachinesPanel";
import RecoveryToolkit from "@/components/alignment/RecoveryToolkit";
import CalibrationPanel from "@/components/alignment/CalibrationPanel";
import AlignmentRetrofitRoadmap from "@/components/alignment/AlignmentRetrofitRoadmap";
import AlignmentSettings from "@/components/alignment/AlignmentSettings";
import CustomerFormDialog from "@/components/customers/CustomerFormDialog";
import VehicleFormDialog from "@/components/vehicles/VehicleFormDialog";
import { createAlignmentSession, createRecoveryCase, deleteAlignmentMachine, deleteCalibration, deleteRecoveryCase, registerAlignmentMachine, saveAlignmentMeasurements, saveAlignmentReport, saveCalibration, updateAlignmentMachine, updateCalibration, updateRecoveryCase } from "@/services/alignmentCenterControl";

export default function Alignment() {
  const [tab,setTab]=useState("overview"),[data,setData]=useState({}),[session,setSession]=useState(null),[measurements,setMeasurements]=useState([]),[customerOpen,setCustomerOpen]=useState(false),[vehicleOpen,setVehicleOpen]=useState(false),[loading,setLoading]=useState(true);
  const navigate=useNavigate(),{toast}=useToast();
  const load=async()=>{setLoading(true);const user=await base44.auth.me();const [machines,profiles,calibrations,cases,sessions,customers,vehicles,orders,reports]=await Promise.all([base44.entities.AlignmentMachine.filter({shop_owner_email:user.email},"-created_date",200),base44.entities.MachineProfile.list(),base44.entities.CalibrationRecord.filter({shop_owner_email:user.email},"-created_date",200),base44.entities.RecoveryCase.filter({shop_owner_email:user.email},"-created_date",200),base44.entities.AlignmentSession.filter({shop_owner_email:user.email},"-created_date",200),base44.entities.Customer.filter({created_by:user.email},"-created_date",10000),base44.entities.Vehicle.filter({created_by:user.email},"-created_date",10000),base44.entities.RepairOrder.filter({created_by:user.email},"-created_date",10000),base44.entities.AlignmentReport.filter({shop_owner_email:user.email},"-created_date",200)]);setData({user,machines,profiles,calibrations,cases,sessions,customers,vehicles,orders,reports});setSession(current=>current? sessions.find(s=>s.id===current.id)||current:sessions[0]||null);setLoading(false);};
  useEffect(()=>{load();},[]);
  useEffect(()=>{if(!session){setMeasurements([]);return;}base44.entities.AlignmentMeasurement.filter({alignment_session_id:session.id},"created_date",100).then(setMeasurements);},[session]);
  const customer=useMemo(()=>data.customers?.find(x=>x.id===session?.customer_id),[data.customers,session]),vehicle=useMemo(()=>data.vehicles?.find(x=>x.id===session?.vehicle_id),[data.vehicles,session]),machine=useMemo(()=>data.machines?.find(x=>x.id===session?.machine_id),[data.machines,session]),order=useMemo(()=>data.orders?.find(x=>x.id===(session?.repair_order_id)),[data.orders,session]),report=useMemo(()=>data.reports?.find(x=>x.alignment_session_id===session?.id),[data.reports,session]);
  const run=async(action,message)=>{try{await action();await load();toast({title:message});}catch(error){toast({title:"Alignment action failed",description:error?.message||"Try again.",variant:"destructive"});}};
  const createSession=async(form,file)=>run(async()=>{const created=await createAlignmentSession({...form,source_confidence:form.created_from==="manual"?1:undefined},file);setSession(created);setTab("measurements");},"Alignment session created");
  if(loading)return <div className="h-40 flex items-center justify-center text-gray-400">Loading Alignment Brain…</div>;
  const counts={sessions:data.sessions.filter(s=>!["completed","archived"].includes(s.status)).length,machines:data.machines.length,recovery:data.cases.filter(c=>!["recovered","unrecoverable","closed"].includes(c.status)).length,reports:data.reports.length};
  const titles={overview:"Alignment Overview",start:"Start Alignment",measurements:"Measurements",report:"Reports",machines:"Machines",recovery:"Recovery Toolkit",calibration:"Calibration",retrofit:"Retrofit Lab — Roadmap",settings:"Settings"};
  return <div className="space-y-5"><div className="grid lg:grid-cols-[260px_minmax(0,1fr)] gap-5 items-start"><AlignmentWorkspaceNav active={tab} onChange={setTab}/><main className="min-w-0 space-y-5"><header className="flex flex-col sm:flex-row sm:items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-cyan-400">LBC Alignment Brain</p><h1 className="mt-1 text-2xl font-bold text-white">{titles[tab]}</h1></div>{data.sessions.length>0&&<select value={session?.id||""} onChange={e=>setSession(data.sessions.find(s=>s.id===e.target.value))} className="h-9 max-w-sm rounded border border-slate-700 bg-slate-950 px-3 text-sm text-white">{data.sessions.map(s=><option key={s.id} value={s.id}>{data.vehicles.find(v=>v.id===s.vehicle_id)?.year} {data.vehicles.find(v=>v.id===s.vehicle_id)?.make} {data.vehicles.find(v=>v.id===s.vehicle_id)?.model} — {s.status}</option>)}</select>}</header><PhaseGateBanner/>
    {tab==="overview"&&<AlignmentOverview counts={counts} onStart={()=>setTab("start")}/>} {tab==="start"&&<StartSession customers={data.customers} vehicles={data.vehicles} orders={data.orders} machines={data.machines} onCreate={createSession} onAddCustomer={()=>setCustomerOpen(true)} onAddVehicle={()=>setVehicleOpen(true)}/>} {tab==="measurements"&&(session?<MeasurementGrid session={session} measurements={measurements} onSave={rows=>run(()=>saveAlignmentMeasurements(session,rows),"Measurements saved")}/>:<Empty text="Start an alignment session first."/>)} {tab==="report"&&<ReportBuilder session={session} customer={customer} vehicle={vehicle} machine={machine} order={order} measurements={measurements} shop={data.user} report={report} navigate={navigate} onSave={payload=>run(()=>saveAlignmentReport({session,report:payload,repairOrder:order}),order?"Report saved and linked to Repair Order":"Alignment report saved")}/>} {tab==="machines"&&<MachinesPanel hideCalibration machines={data.machines} profiles={data.profiles} calibrations={data.calibrations} onRegister={value=>run(()=>registerAlignmentMachine(value),"Machine registered")} onUpdate={(id,value)=>run(()=>updateAlignmentMachine(id,value),"Machine updated")} onDelete={id=>run(()=>deleteAlignmentMachine(id),"Machine removed")} onCalibrate={value=>run(()=>saveCalibration(value),"Calibration saved")} onUpdateCalibration={(id,value)=>run(()=>updateCalibration(id,value),"Calibration updated")} onDeleteCalibration={id=>run(()=>deleteCalibration(id),"Calibration removed")}/>} {tab==="recovery"&&<RecoveryToolkit machines={data.machines} cases={data.cases} onCreate={value=>run(()=>createRecoveryCase(value),"Recovery case created")} onUpdate={(id,value)=>run(()=>updateRecoveryCase(id,value),"Recovery case updated")} onDelete={id=>run(()=>deleteRecoveryCase(id),"Recovery case removed")}/>} {tab==="calibration"&&<CalibrationPanel machines={data.machines} calibrations={data.calibrations} onCreate={value=>run(()=>saveCalibration(value),"Calibration saved")} onUpdate={(id,value)=>run(()=>updateCalibration(id,value),"Calibration updated")} onDelete={id=>run(()=>deleteCalibration(id),"Calibration removed")}/>} {tab==="retrofit"&&<AlignmentRetrofitRoadmap/>} {tab==="settings"&&<AlignmentSettings/>}</main></div>
    <CustomerFormDialog open={customerOpen} onClose={()=>setCustomerOpen(false)} customer={null} onSaved={load}/><VehicleFormDialog open={vehicleOpen} onClose={()=>setVehicleOpen(false)} vehicle={null} customers={data.customers} onSaved={load}/></div>;
}
function Empty({text}){return <div className="rounded-xl border border-dashed border-gray-700 p-10 text-center text-gray-400">{text}</div>}