import React, { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useToast } from "@/components/ui/use-toast";
import PhaseGateBanner from "@/components/alignment/PhaseGateBanner";
import AlignmentOverview from "@/components/alignment/AlignmentOverview";
import StartSession from "@/components/alignment/StartSession";
import MeasurementGrid from "@/components/alignment/MeasurementGrid";
import ReportBuilder from "@/components/alignment/ReportBuilder";
import MachinesPanel from "@/components/alignment/MachinesPanel";
import RecoveryToolkit from "@/components/alignment/RecoveryToolkit";
import CustomerFormDialog from "@/components/customers/CustomerFormDialog";
import VehicleFormDialog from "@/components/vehicles/VehicleFormDialog";
import { createAlignmentSession, createRecoveryCase, deleteAlignmentMachine, deleteCalibration, deleteRecoveryCase, registerAlignmentMachine, saveAlignmentMeasurements, saveAlignmentReport, saveCalibration, updateAlignmentMachine, updateCalibration, updateRecoveryCase } from "@/services/alignmentCenterControl";

export default function Alignment() {
  const [tab,setTab]=useState("overview"),[data,setData]=useState({}),[session,setSession]=useState(null),[measurements,setMeasurements]=useState([]),[customerOpen,setCustomerOpen]=useState(false),[vehicleOpen,setVehicleOpen]=useState(false),[loading,setLoading]=useState(true);
  const navigate=useNavigate(),{toast}=useToast();
  const load=async()=>{setLoading(true);const user=await base44.auth.me();const [machines,profiles,calibrations,cases,sessions,customers,vehicles,orders,reports]=await Promise.all([base44.entities.AlignmentMachine.filter({shop_owner_email:user.email},"-created_date",200),base44.entities.MachineProfile.list(),base44.entities.CalibrationRecord.filter({shop_owner_email:user.email},"-created_date",200),base44.entities.RecoveryCase.filter({shop_owner_email:user.email},"-created_date",200),base44.entities.AlignmentSession.filter({shop_owner_email:user.email},"-created_date",200),base44.entities.Customer.filter({created_by:user.email},"-created_date",10000),base44.entities.Vehicle.filter({created_by:user.email},"-created_date",10000),base44.entities.RepairOrder.filter({created_by:user.email},"-created_date",10000),base44.entities.AlignmentReport.filter({shop_owner_email:user.email},"-created_date",200)]);setData({user,machines,profiles,calibrations,cases,sessions,customers,vehicles,orders,reports});setSession(current=>current? sessions.find(s=>s.id===current.id)||current:sessions[0]||null);setLoading(false);};
  useEffect(()=>{load();},[]);
  useEffect(()=>{if(!session){setMeasurements([]);return;}base44.entities.AlignmentMeasurement.filter({alignment_session_id:session.id},"created_date",100).then(setMeasurements);},[session]);
  const customer=useMemo(()=>data.customers?.find(x=>x.id===session?.customer_id),[data.customers,session]),vehicle=useMemo(()=>data.vehicles?.find(x=>x.id===session?.vehicle_id),[data.vehicles,session]),machine=useMemo(()=>data.machines?.find(x=>x.id===session?.machine_id),[data.machines,session]),order=useMemo(()=>data.orders?.find(x=>x.id===(session?.repair_order_id)),[data.orders,session]),report=useMemo(()=>data.reports?.find(x=>x.alignment_session_id===session?.id),[data.reports,session]);
  const run=async(action,message)=>{try{await action();await load();toast({title:message});}catch(error){toast({title:"Alignment action failed",description:error?.message||"Try again.",variant:"destructive"});}};
  const createSession=async(form,file)=>run(async()=>{const created=await createAlignmentSession({...form,source_confidence:form.created_from==="manual"?1:undefined},file);setSession(created);setTab("measurements");},"Alignment session created");
  if(loading)return <div className="h-40 flex items-center justify-center text-gray-400">Loading Alignment Companion…</div>;
  return <div className="space-y-5"><div><h1 className="text-2xl font-bold text-white">LBC Alignment</h1><p className="text-gray-400">Alignment Architect / Companion</p></div><PhaseGateBanner />{data.sessions?.length>0&&<div className="flex items-center gap-2"><span className="text-sm text-gray-400">Active session:</span><select value={session?.id||""} onChange={e=>setSession(data.sessions.find(s=>s.id===e.target.value))} className="h-9 max-w-md rounded border border-gray-700 bg-gray-900 px-3 text-sm text-white">{data.sessions.map(s=><option key={s.id} value={s.id}>{data.vehicles.find(v=>v.id===s.vehicle_id)?.year} {data.vehicles.find(v=>v.id===s.vehicle_id)?.make} {data.vehicles.find(v=>v.id===s.vehicle_id)?.model} — {s.status}</option>)}</select></div>}
    <Tabs value={tab} onValueChange={setTab}><TabsList className="w-full justify-start overflow-x-auto bg-gray-900 h-auto p-1">{[["overview","Overview"],["start","Start Session"],["measurements","Measurements"],["report","Report Builder"],["machines","Machines"],["recovery","Recovery Toolkit"]].map(([v,l])=><TabsTrigger key={v} value={v} className="shrink-0">{l}</TabsTrigger>)}</TabsList><TabsContent value="overview"><AlignmentOverview onStart={()=>setTab("start")} /></TabsContent><TabsContent value="start"><StartSession customers={data.customers} vehicles={data.vehicles} orders={data.orders} machines={data.machines} onCreate={createSession} onAddCustomer={()=>setCustomerOpen(true)} onAddVehicle={()=>setVehicleOpen(true)} /></TabsContent><TabsContent value="measurements">{session?<MeasurementGrid session={session} measurements={measurements} onSave={rows=>run(()=>saveAlignmentMeasurements(session,rows),"Measurements saved")} />:<Empty text="Start an alignment session first." />}</TabsContent><TabsContent value="report"><ReportBuilder session={session} customer={customer} vehicle={vehicle} machine={machine} order={order} measurements={measurements} shop={data.user} report={report} navigate={navigate} onSave={payload=>run(()=>saveAlignmentReport({session,report:payload,repairOrder:order}),order?"Report saved and linked to Repair Order":"Alignment report saved")} /></TabsContent><TabsContent value="machines"><MachinesPanel machines={data.machines} profiles={data.profiles} calibrations={data.calibrations} onRegister={value=>run(()=>registerAlignmentMachine(value),"Machine registered")} onUpdate={(id,value)=>run(()=>updateAlignmentMachine(id,value),"Machine updated")} onDelete={id=>run(()=>deleteAlignmentMachine(id),"Machine removed")} onCalibrate={value=>run(()=>saveCalibration(value),"Calibration saved")} onUpdateCalibration={(id,value)=>run(()=>updateCalibration(id,value),"Calibration updated")} onDeleteCalibration={id=>run(()=>deleteCalibration(id),"Calibration removed")} /></TabsContent><TabsContent value="recovery"><RecoveryToolkit machines={data.machines} cases={data.cases} onCreate={value=>run(()=>createRecoveryCase(value),"Recovery case created")} onUpdate={(id,value)=>run(()=>updateRecoveryCase(id,value),"Recovery case updated")} onDelete={id=>run(()=>deleteRecoveryCase(id),"Recovery case removed")} /></TabsContent></Tabs>
    <CustomerFormDialog open={customerOpen} onClose={()=>setCustomerOpen(false)} customer={null} onSaved={load} /><VehicleFormDialog open={vehicleOpen} onClose={()=>setVehicleOpen(false)} vehicle={null} customers={data.customers} onSaved={load} /></div>;
}
function Empty({text}){return <div className="rounded-xl border border-dashed border-gray-700 p-10 text-center text-gray-400">{text}</div>}