import React, { useState } from "react";
import { CalendarPlus, CheckCircle2 } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { vehicleName } from "@/components/customer-dashboard/portalUtils";

export default function BookingDialog({ open, vehicles, selectedVehicleId, onClose, onSubmit }) {
  const [form, setForm] = useState({ vehicle_id: selectedVehicleId === "all" ? vehicles[0]?.id || "" : selectedVehicleId, service_type: "", date: "", time_slot: "", notes: "" }); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(""); try { await onSubmit(form); setSuccess("Your appointment request is booked."); } catch (reason) { setError(reason.message); } finally { setBusy(false); } };
  return <Dialog open={open}><DialogContent className="portal-dialog max-w-lg" onInteractOutside={(event) => event.preventDefault()} onEscapeKeyDown={(event) => event.preventDefault()}><DialogHeader><div className="portal-icon-box mb-3"><CalendarPlus /></div><DialogTitle className="text-2xl text-portal-text">Book an appointment</DialogTitle><DialogDescription className="text-portal-muted">Send a real service booking to your shop.</DialogDescription></DialogHeader>{success ? <div className="portal-success-state"><CheckCircle2 /><h3>{success}</h3><button className="portal-primary-button" onClick={onClose}>Done</button></div> : <form className="portal-form" onSubmit={submit}><label>Vehicle<select value={form.vehicle_id} onChange={(event) => setForm({ ...form, vehicle_id: event.target.value })} required><option value="">Choose a vehicle</option>{vehicles.map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicleName(vehicle)}</option>)}</select></label><label>Service needed<input value={form.service_type} onChange={(event) => setForm({ ...form, service_type: event.target.value })} placeholder="Oil change, tire service, inspection…" required /></label><div className="grid gap-3 sm:grid-cols-2"><label>Date<input type="date" value={form.date} min={new Date().toISOString().slice(0, 10)} onChange={(event) => setForm({ ...form, date: event.target.value })} required /></label><label>Preferred time<input value={form.time_slot} onChange={(event) => setForm({ ...form, time_slot: event.target.value })} placeholder="10:00 AM" required /></label></div><label>Notes<textarea rows="3" value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} placeholder="Anything the shop should know?" /></label>{error && <p className="portal-inline-error">{error} Please review and try again.</p>}<div className="flex gap-3"><button type="button" className="portal-secondary-button flex-1" onClick={onClose}>Cancel</button><button className="portal-primary-button flex-1" disabled={busy}>{busy ? "Booking…" : "Book appointment"}</button></div></form>}</DialogContent></Dialog>;
}