import React from "react";
import { AlertTriangle, Camera, Gauge, ScanLine, Wrench } from "lucide-react";
import StatusChip from "@/components/customer-dashboard/StatusChip";
import { formatDate, maskVin, vehicleName } from "@/components/customer-dashboard/portalUtils";

export default function CarsView({ vehicle, vehicles, data, onOpen, onBook }) {
  if (!vehicle) return <div className="portal-empty portal-panel"><Gauge /><h3>Select one vehicle</h3><p>Choose a vehicle above to see its full secure history.</p></div>;
  const photos = Object.entries(vehicle.intake_photos || {}).filter(([, value]) => value);
  return <div className="portal-view-grid"><section className="portal-panel"><p className="portal-eyebrow">Vehicle profile</p><h2>{vehicleName(vehicle)}</h2><div className="portal-spec-grid">{[["VIN", maskVin(vehicle.vin)], ["Mileage", vehicle.mileage != null ? `${Number(vehicle.mileage).toLocaleString()} km` : "Not recorded"], ["Engine", vehicle.engine_type], ["Fuel", vehicle.fuel_type], ["Drive", vehicle.drive_type], ["Last service", vehicle.last_service_date ? formatDate(vehicle.last_service_date) : "Not recorded"]].filter(([, value]) => value).map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>{photos.length > 0 && <><h3 className="portal-subheading"><Camera />Vehicle photos</h3><div className="portal-photo-grid">{photos.map(([label, url]) => <figure key={label}><img src={url} alt={`${vehicleName(vehicle)} ${label}`} /><figcaption>{label}</figcaption></figure>)}</div></>}<button className="portal-primary-button mt-5" onClick={onBook}>Book service</button></section><section className="portal-panel"><p className="portal-eyebrow">Vehicle care</p><h2>Recommendations & diagnostics</h2><div className="portal-record-list">{data.recommendations.map((record) => <button key={record.id} onClick={() => onOpen("recommendation", record)}><AlertTriangle /><div className="min-w-0 flex-1"><h3>{record.title}</h3><p>{record.description || "Shop recommendation"}</p></div><StatusChip status={record.urgency} /></button>)}{data.diagnostics.map((record) => <button key={record.id} onClick={() => onOpen("diagnostic", record)}><ScanLine /><div className="min-w-0 flex-1"><h3>Diagnostic Scan</h3><p>{record.dtc_codes?.length || 0} codes · {formatDate(record.scan_timestamp)}</p></div><StatusChip status={record.status} /></button>)}{data.orders.map((record) => <button key={record.id} onClick={() => onOpen("order", record)}><Wrench /><div className="min-w-0 flex-1"><h3>{record.description || "Service record"}</h3><p>{formatDate(record.created_date)}</p></div><StatusChip status={record.status} /></button>)}{!data.recommendations.length && !data.diagnostics.length && !data.orders.length && <div className="portal-empty"><ScanLine /><h3>No vehicle activity yet</h3><p>Recommendations, scans, and service history appear here.</p></div>}</div></section></div>;
}