import React, { useState } from "react";
import { CheckCircle2, FileText, MessageSquare, Printer, Wrench, XCircle } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import StatusChip from "@/components/customer-dashboard/StatusChip";
import FinancialDocumentBody from "./FinancialDocumentBody";
import EstimateDecisionDialog from "./EstimateDecisionDialog";

export default function CustomerFinancialDocument({ detail, shop, orders, invoices, onClose, onMessage, onDecision, onOpenLinked }) {
  const [decision,setDecision]=useState(""); const [notice,setNotice]=useState(""); if(!detail)return null; const {type,record}=detail; const pending=type==="estimate"&&(record.status==="sent"||record.auth_status==="pending"); const linkedOrder=orders.find(x=>x.id===record.linked_repair_order_id||x.estimate_id===record.id); const linkedInvoice=invoices.find(x=>x.id===record.linked_invoice_id||x.estimate_id===record.id);
  const confirm=async payload=>{const result=await onDecision(record.id,payload);setNotice(result.message);};
  return <><Dialog open><DialogContent className="portal-dialog portal-financial-document" onInteractOutside={e=>e.preventDefault()} onEscapeKeyDown={e=>e.preventDefault()}><DialogHeader><DialogTitle className="text-portal-text">{type==="estimate"?"View Estimate":"View Invoice"}</DialogTitle><DialogDescription><StatusChip status={record.status}/></DialogDescription></DialogHeader><div className="portal-financial-scroll"><FinancialDocumentBody type={type} record={record} shop={shop}/>{notice&&<p className="portal-inline-success"><CheckCircle2/>{notice}</p>}</div><div className="portal-financial-bar">{pending&&<><button className="portal-secondary-button" onClick={()=>setDecision("decline")}><XCircle/>Decline</button><button className="portal-primary-button" onClick={()=>setDecision("approve")}><CheckCircle2/>Approve</button></>}{linkedOrder&&<button className="portal-secondary-button" onClick={()=>onOpenLinked("order",linkedOrder)}><Wrench/>View Repair Order</button>}{linkedInvoice&&<button className="portal-secondary-button" onClick={()=>onOpenLinked("invoice",linkedInvoice)}><FileText/>View Invoice</button>}<button className="portal-secondary-button" onClick={()=>onMessage(`${type==="estimate"?"Estimate":"Invoice"} #${type==="estimate"?record.estimate_number:record.invoice_number}`)}><MessageSquare/>Message Shop</button><button className="portal-secondary-button" onClick={()=>window.print()}><Printer/>Print / Save PDF</button><button className="portal-secondary-button" onClick={onClose}>Close</button></div></DialogContent></Dialog>{decision&&<EstimateDecisionDialog estimate={record} decision={decision} customerName={record.customer_decision_name||shop?.customer_name} onClose={()=>setDecision("")} onConfirm={confirm}/>}</>;
}