import React, { useState } from "react";
import { CheckCircle2, XCircle } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { formatMoney } from "@/components/customer-dashboard/portalUtils";

export default function EstimateDecisionDialog({ estimate, decision, customerName, onClose, onConfirm }) {
  const [name,setName]=useState(customerName||""); const [note,setNote]=useState(""); const [confirmed,setConfirmed]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [key]=useState(()=>crypto.randomUUID());
  if(!estimate||!decision)return null; const approve=decision==="approve";
  const submit=async()=>{setBusy(true);setError("");try{await onConfirm({decision,signer_name:name,note,confirmed,idempotency_key:key});onClose();}catch(reason){setError(reason.message||"Decision unavailable");}finally{setBusy(false);}};
  return <Dialog open><DialogContent className="portal-dialog" onInteractOutside={e=>e.preventDefault()} onEscapeKeyDown={e=>e.preventDefault()}><DialogHeader><DialogTitle className="text-portal-text">{approve?"Approve Estimate":"Decline Estimate"}</DialogTitle><DialogDescription className="text-portal-muted">Estimate #{estimate.estimate_number||"—"} · {estimate.vehicle_info||"Vehicle"} · {formatMoney(estimate.grand_total)}</DialogDescription></DialogHeader><p className="portal-detail-copy">{approve?"Approval records your authorization. The shop can then convert this estimate into a Repair Order.":"Declining records your decision for the shop. It does not delete the estimate."}</p><div className="portal-form"><label>Signer / customer name<input value={name} onChange={e=>setName(e.target.value)} /></label><label>Optional note<textarea rows="3" value={note} onChange={e=>setNote(e.target.value)} /></label><label className="portal-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I confirm this decision for the estimate shown above.</span></label></div>{error&&<p className="portal-inline-error">{error}</p>}<div className="portal-financial-bar"><button className="portal-secondary-button" disabled={busy} onClick={onClose}>Cancel</button><button className={approve?"portal-primary-button":"portal-danger-button"} disabled={busy||!confirmed||name.trim().length<2} onClick={submit}>{approve?<CheckCircle2/>:<XCircle/>}{busy?"Saving…":approve?"Approve Estimate":"Decline Estimate"}</button></div></DialogContent></Dialog>;
}