import React, { useState } from "react";
import { ArrowLeft, CalendarDays, CheckCircle2, FileText, MessageSquare, Receipt, Wrench, XCircle } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import StatusChip from "@/components/customer-dashboard/StatusChip";
import { formatDate, formatMoney, RECORD_CONFIG, titleCase } from "@/components/customer-dashboard/portalUtils";

const DetailRows = ({ type, record }) => {
  if (type === "order") return <><p className="portal-detail-copy">{titleCase(record.description)}</p>{record.estimated_completion && <p>Estimated completion: <strong>{formatDate(record.estimated_completion)}</strong></p>}</>;
  if (type === "appointment") return <><p className="portal-detail-copy">{titleCase(record.service_type)}</p><p>{formatDate(record.date)}{record.time_slot ? ` at ${record.time_slot}` : ""}</p></>;
  if (type === "recommendation") return <><p className="portal-detail-copy">{record.description || "Your shop recommends reviewing this service."}</p>{record.estimated_cost != null && <p>Estimated amount: <strong>{formatMoney(record.estimated_cost)}</strong></p>}</>;
  if (type === "diagnostic") return <div className="portal-line-items">{record.dtc_codes?.length ? record.dtc_codes.map((code) => <div key={code.code}><span>{code.code}</span><strong>{code.description || "Diagnostic code recorded"}</strong></div>) : <p>No diagnostic codes were recorded.</p>}</div>;
  const items = type === "estimate" ? [...(record.labor_items || []).map((item) => ({ label: item.description, amount: item.total })), ...(record.parts_items || []).map((item) => ({ label: item.name, amount: item.total }))] : record.line_items?.map((item) => ({ label: item.description, amount: item.total })) || [];
  return <><div className="portal-line-items">{items.length ? items.map((item, index) => <div key={`${item.label}-${index}`}><span>{item.label || "Service item"}</span><strong>{formatMoney(item.amount)}</strong></div>) : <p>No itemized customer-facing details are available.</p>}</div><div className="portal-total"><span>{type === "invoice" ? "Invoice total" : "Estimate total"}</span><strong>{formatMoney(type === "invoice" ? record.total : record.grand_total)}</strong></div>{type === "invoice" && <div className="portal-balance"><span>Paid {formatMoney(record.amount_paid)}</span><strong>Balance {formatMoney(record.balance_due)}</strong></div>}</>;
};

export default function RecordDetailDialog({ detail, onClose, onMessage, onEstimateDecision }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  if (!detail) return null; const { type, record } = detail; const config = RECORD_CONFIG[type]; const financial = ["order", "estimate", "invoice"].includes(type);
  const decide = async (decision) => { setBusy(true); setError(""); try { await onEstimateDecision(record.id, decision); setSuccess(`Estimate ${decision === "approve" ? "approved" : "declined"}.`); } catch (event) { setError(event.message); } finally { setBusy(false); } };
  const icon = type === "invoice" ? Receipt : type === "appointment" ? CalendarDays : type === "order" ? Wrench : FileText;
  return <Dialog open={Boolean(detail)} onOpenChange={(open) => { if (!open) onClose(); }}><DialogContent className="portal-dialog portal-detail-dialog" onInteractOutside={(event) => event.preventDefault()} onEscapeKeyDown={(event) => event.preventDefault()}><div className="flex justify-start mb-3"><button className="portal-secondary-button" onClick={onClose}><ArrowLeft /><span>Back</span></button></div><DialogHeader><div className="portal-icon-box mb-3">{React.createElement(icon)}</div><DialogTitle className="text-2xl text-portal-text">{config?.label || "Record"}</DialogTitle><DialogDescription className="flex flex-wrap items-center gap-2 text-portal-muted"><span>{formatDate(record.date || record.scan_timestamp || record.created_date)}</span><StatusChip status={record.status || record.urgency} /></DialogDescription></DialogHeader><div className="portal-detail-body"><DetailRows type={type} record={record} />{error && <p className="portal-inline-error">{error} Try again when you’re ready.</p>}{success && <p className="portal-inline-success"><CheckCircle2 />{success}</p>}</div>{financial && <div className="portal-financial-bar">{type === "estimate" && !["approved", "declined", "invoiced", "cancelled"].includes(record.status) ? <><button className="portal-secondary-button" disabled={busy} onClick={() => decide("decline")}><XCircle />Decline</button><button className="portal-primary-button" disabled={busy} onClick={() => decide("approve")}><CheckCircle2 />Approve</button></> : <button className="portal-secondary-button" onClick={onMessage}><MessageSquare />Message Shop</button>}<button className="portal-secondary-button" onClick={onClose}>Close</button></div>} {!financial && <button className="portal-secondary-button mt-4 w-full" onClick={onClose}>Close</button>}</DialogContent></Dialog>;
}