import React from "react";
import { ChevronRight, FolderOpen } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import StatusChip from "@/components/customer-dashboard/StatusChip";
import { formatDate, formatMoney, statusLabel } from "@/components/customer-dashboard/portalUtils";

const config = { orders: ["Repair Orders", "order"], estimates: ["Estimates", "estimate"], invoices: ["Invoices", "invoice"], appointments: ["Appointments", "appointment"] };
export default function RecordListDialog({ type, rows, onClose, onOpen, onEmptyAction }) {
  if (!type) return null; const [title, recordType] = config[type];
  return <Dialog open={Boolean(type)} onOpenChange={(open) => { if (!open) onClose(); }}><DialogContent className="portal-dialog portal-list-dialog" onInteractOutside={(event) => event.preventDefault()} onEscapeKeyDown={(event) => event.preventDefault()}><DialogHeader><DialogTitle className="text-2xl text-portal-text">{title}</DialogTitle><DialogDescription className="text-portal-muted">Showing records for your selected vehicle view.</DialogDescription></DialogHeader><div className="portal-record-list">{rows.length ? rows.map((row) => <button key={row.id} onClick={() => onOpen(recordType, row)}><div className="min-w-0 flex-1"><h3>{row.description || row.service_type || row.service_reason || row.vehicle_info || title.slice(0, -1)}</h3><p>{formatDate(row.date || row.created_date)}{type === "invoices" ? ` · ${formatMoney(row.balance_due)} balance` : ""}</p></div><StatusChip status={row.status || "pending"} /><ChevronRight /></button>) : <div className="portal-empty"><FolderOpen /><h3>No {title.toLowerCase()} here</h3><p>{type === "appointments" ? "You can request service whenever you need it." : `There are no ${title.toLowerCase()} for this vehicle view.`}</p>{type === "appointments" && <button className="portal-primary-button" onClick={onEmptyAction}>Book an appointment</button>}</div>}</div><button className="portal-secondary-button mt-4 w-full" onClick={onClose}>Close</button></DialogContent></Dialog>;
}